/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Message, MessageInterface } from "../Message";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "_originDomain",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "_sender",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "_nonce",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "_destinationDomain",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "_recipient",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "_messageBody",
        type: "bytes",
      },
    ],
    name: "UpdateValue",
    type: "event",
  },
];

const _bytecode =
  "0x60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212202e55e2d39f0ade6a283541bde00b15d6f91aa7f41740a67027900eaef8b01fe764736f6c63430007060033";

export class Message__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Message> {
    return super.deploy(overrides || {}) as Promise<Message>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Message {
    return super.attach(address) as Message;
  }
  connect(signer: Signer): Message__factory {
    return super.connect(signer) as Message__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MessageInterface {
    return new utils.Interface(_abi) as MessageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Message {
    return new Contract(address, _abi, signerOrProvider) as Message;
  }
}
