/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MessageInterface extends ethers.utils.Interface {
  functions: {};

  events: {
    "UpdateValue(uint32,bytes32,uint32,uint32,bytes32,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "UpdateValue"): EventFragment;
}

export type UpdateValueEvent = TypedEvent<
  [number, string, number, number, string, string] & {
    _originDomain: number;
    _sender: string;
    _nonce: number;
    _destinationDomain: number;
    _recipient: string;
    _messageBody: string;
  }
>;

export class Message extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MessageInterface;

  functions: {};

  callStatic: {};

  filters: {
    "UpdateValue(uint32,bytes32,uint32,uint32,bytes32,bytes)"(
      _originDomain?: null,
      _sender?: null,
      _nonce?: null,
      _destinationDomain?: null,
      _recipient?: null,
      _messageBody?: null
    ): TypedEventFilter<
      [number, string, number, number, string, string],
      {
        _originDomain: number;
        _sender: string;
        _nonce: number;
        _destinationDomain: number;
        _recipient: string;
        _messageBody: string;
      }
    >;

    UpdateValue(
      _originDomain?: null,
      _sender?: null,
      _nonce?: null,
      _destinationDomain?: null,
      _recipient?: null,
      _messageBody?: null
    ): TypedEventFilter<
      [number, string, number, number, string, string],
      {
        _originDomain: number;
        _sender: string;
        _nonce: number;
        _destinationDomain: number;
        _recipient: string;
        _messageBody: string;
      }
    >;
  };

  estimateGas: {};

  populateTransaction: {};
}
